### ISSUE TITLE
Add css file to bower.main please

### ISSUE THREAD

**Issue by TrySound** [Stryzhevskyi/rangeSlider#1]

**Comment by Stryzhevskyi** [comment]
Done.

**Comment by TrySound** [comment]
No IE8! Cool :)
But, do not need to include minified versions.
I use main-bower-files for building my projects. It's parses all dependencies with main fields. So code mustn't be loaded twice. Just non-minified versions of files.

[bower.spec](https://github.com/bower/bower.json-spec#main)

**Comment by Stryzhevskyi** [comment]
Sorry for delay, I made those changes today.

**Comment by TrySound** [comment]
@Stryzhevskyi Thanks!
