### ISSUE TITLE
Decimal Step Issue

### ISSUE THREAD

**Issue by flythird** [Stryzhevskyi/rangeSlider#10]
hello from Frog Land (or cheese land : France Perpignan) !

I use your plugin with an angular application, this is the best plugin i can easily use, thank's to you.

 but i have a problem: 
-   I use these parameters : {min = 0, max = 100, step = 0.1,value = 0}
-   I use the mouse and I am not able to select the 
  10.0  or 20.0 or 30.0 .... value ?????? 
  
  for example, to select 10, it's not possible, i turn around the decimal value, i can get 9.9 or 10.1 
  but never the 10 value. 
  
  when you set the value to 10 dynamically or use the default value this is good for the initialisation....
  but the same problem continue.
  
  i don't want today have a look on the code because i can't,   but i think it could be easily solved by the 
  creator. Maybe this issue has already its solution.
  Can you help me ?

thanks for your attention, and have a nice day

**Comment by Stryzhevskyi** [comment]
Hi.
You are welcome!
I've reproduced your issue, it's annoying, when handle can't stop in certain position.
I think [this is](https://github.com/Stryzhevskyi/rangeSlider/commit/e87f0ac6ba762f11bfde7fa6e570f3d99b0328a2) one of reasonable solutions : new options "stick" have been added, it's array of two number [stickTo, stickRadius]: 
**stickTo** - define which Nth number handle will stick to;
**stickRadius** - size of sticky area.
It can be attribute stick="stickTo stickRadius" (separated with space) too.
Example [here](https://stryzhevskyi.github.io/rangeSlider/) (Stick example). I recommend to use stickRadius = step*1.5 if you need good precision, otherwise bigger value for better UX.

Let me know, if this feature will help you.

**Comment by flythird** [comment]
Hello ! or bonjour !

I am not sure to understand the stick use
I think it's coming from my english or my brain

what kind of stick parameter values  do you you use for my sample ?
{min = 0, max = 100, step = 0.1,value = 0}
if you want the cursor to pass by the decimal values.

In fact i don't understand. In your sample 'floating' : you don't use 'stick'  parameter.
{min = 0, max = 100, step = 0.1,value = 0.0} 

div style="width:540px; height:94px;"  br
input type="range" min="0" max="100" step="0.1" value="0" data-rangeSlider
output /output
div
with this div style : style="width:540px; height:94px;"
just the width is a constraint the <br/> is for my label place

The 0.3.9  correct a little the problem  but the stick using is mysterious just for me i guess !!!!!!!!!!!!!!!!
Is this parameter force the cursor to pass by  the arounded values defined by steps ?

just for my comprehension do you have a drawing ? 

For the moment : if i use a stick="1 0.1" and my step="0.1" i shouldn't  miss any integer value ???
No i miss a lot of integer values.
Without stick i miss all the integers ????

i didn't see the code and i think there is a problem with the precision step and...
 by experience i think it's not unsolvable. 
For my sample you should have 1000 points with 540 pixels width div
May be if you set stick to : stick="1 0.27" i don't miss any integer value but it's not a dream or perfect.

I think a lot of people will have this issue. An integer graphic step should be computed and limited.

thanks for your attention, and have a nice day, or evening or night...

**Comment by Stryzhevskyi** [comment]
Hi

>  In your sample 'floating' : you don't use 'stick' parameter.

Look at "Stick example"

> Handle will stick to Nth number in X radius, 10 and 0.5 in example

On this gif i use {min: 0, max: 100, value : 0, stick: [10, **1**], step: 0.1}
![screencast 2016-05-17 22-10-50](https://cloud.githubusercontent.com/assets/1058402/15335866/b51aa186-1c7c-11e6-9321-0e05c47bc641.gif)
First stick's number means that handle will stick to 10*x values, where x - integers > 0

Second number means radius in which value will shift from real to nearest 10*x (9 < value < 11 will transform to 10), in example it's big (1) 
for illustration, as you mention, you can use 0.27 (actually even 0.11 is enough for me to be able select 10, 20 ...). But, unfortunately, this feature will prevent selecting another value (not center) inside sticky area.

**Comment by flythird** [comment]
hello ! yes yes ok but.....

now the explaination help me, sure, ouf.... it sticks. thanks a lot and not only for your answer but for the time you spent to do your gif - I'll try your parameter 

i wonder....to rent or sale your plugin (or not to be bothered)
I asked the question. 
you 'll have the same questions in the future i think.... except the reading of this discussion......
my need was having the 1000 points between [0,100] and the possibility to see them.

in the future do you think possible your plugin to dynamically compute the stick parameter in order to
avoid the users an headache. (because sometime a person can have the same brain as me or less... 
the very poors...beasts by example, birds or monkeys)
think about those who are not einstein ! ok

thanks again ans seriously i use your plugin in my whole application
have a nice "what you want" 

alan from perpignan, somewhere, where you take the best in the world temperature

**Comment by flythird** [comment]
tcho again

i tried your parameters and of course stick="10 1" has the behavior you describe with your gif.

i am not able to set the 15 value.. Ok for 10,20,30...90 and of course 100 and because of stick. but no integers 15 7 8 22.....

i tried stick="1 0.11" it is not perfect but i take.

bye
