### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollHeight' of undefined   

### ISSUE THREAD

**Issue by vahidhedayati** [Stryzhevskyi/rangeSlider#14]
When running your code unsure what exact cause is am using within jquery ui tabs but upon window resize chrome keeps throwing above error. As a work around the if statement added 
Line 103:

Was:
```
function isHidden(element) {
   return !!(element.offsetWidth === 0 || element.offsetHeight === 0 || element.open === false);
}
```

To: 
```
function isHidden(element) {
            if (element.offsetWidth && element.offsetHeight ) {
                return !!(element.offsetWidth === 0 || element.offsetHeight === 0 || element.open === false);
            } else {
               return true
            }
        }
```

appears to fix the issue, but i presume some other thing is causing underlying issue

**Comment by Stryzhevskyi** [comment]
It seems, slider is detached from DOM (at the moment of window resize). Ensure that .destroy() invoked before removing element from DOM.
There was similar issue with React: #13
