### ISSUE TITLE
Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by adampatterson** [Stryzhevskyi/rangeSlider#16]
I had updated my local code to use the update method and was getting "Cannot read property 'update' of undefined"

I started completely from scratch using the example under [Usage](https://github.com/Stryzhevskyi/rangeSlider#usage) and am getting the same error.

I am using v0.3.11, there is a lot of other javascript but from what I can tell its not conflicting.

Any insight would be appreciated.

**Comment by adampatterson** [comment]
I was being ridiculous and calling an outside reference to my slider. Its all good now!

**Comment by salehmosleh** [comment]
how you fix it ? i have same error. #28

**Comment by salehmosleh** [comment]
how you fix it ? i have same error. #28

**Comment by salehmosleh** [comment]
how you fix it ? i have same error. #28

**Comment by adampatterson** [comment]
@salehmosleh sorry, I don't recall what I did to fix the issue.

**Comment by Stryzhevskyi** [comment]
Check answer: https://github.com/Stryzhevskyi/rangeSlider/issues/28#issuecomment-343684912

**Comment by salehmosleh** [comment]
@Stryzhevskyi , thanks.
