### ISSUE TITLE
Not Working IN IE9

### ISSUE THREAD

**Issue by krish-0404** [Stryzhevskyi/rangeSlider#18]
Range slider not slide in IE9

**Comment by krish-0404** [comment]
Please help as. is there any solutions?

**Comment by Stryzhevskyi** [comment]
Check v 0.4.0, please. Should be fixed. 

![screencast 2017-06-02 00-41-03](https://cloud.githubusercontent.com/assets/1058402/26702380/67b01b38-472d-11e7-9808-5e01e60d63bf.gif)
