### ISSUE TITLE
No dist or source files in version 0.4.0 using Bower

### ISSUE THREAD

**Issue by adampatterson** [Stryzhevskyi/rangeSlider#20]
Updating to version 0.4.0 with bower does not contain source
0.3.10 and 0.3.11 both have a `/dist` folder.

**0.3.10 and 0.3.11**
![image](https://cloud.githubusercontent.com/assets/31537/26691031/e150384e-46b8-11e7-9476-9db36430d287.png)

**update to 0.4.0**
![image](https://cloud.githubusercontent.com/assets/31537/26690989/bb9aead6-46b8-11e7-859c-cb44bc170794.png)

**Comment by Stryzhevskyi** [comment]
:confused:
Check v 0.4.1, filenames has been changed to kebab-case.

**Comment by adampatterson** [comment]
Closes #20 Thanks, That did the trick!
