### ISSUE TITLE
How to add Prefix and Suffix

### ISSUE THREAD

**Issue by berniebetgcarpio** [Stryzhevskyi/rangeSlider#21]
Hello,

Is it possible to add Prefix or Suffix on the output? like
$12,000 or 123%

Thanks

**Comment by Stryzhevskyi** [comment]
Hi,

[The range state represents a control for setting the element's value to a string representing a number](https://www.w3.org/wiki/HTML/Elements/input/range), hence browser which support type="range" will drop any suffix and ignore numbers with prefix completely.
You can easily format value and render it on page like this:
```js
inputElement.addEventListener('input', function (e) {
    outputElement.textContent = e.target.value + '%';
}, false);
```
where
- _inputElement_ - input: HTMLElement - rangeSliders' input (actually any input)
- _outputElement_ - can be span/p/a etc..

**Comment by berniebetgcarpio** [comment]
Thanks

**Comment by forzapilot** [comment]
Any chance you could show a working example?

I'd really appreciate it if you could.

Thanks!
