### ISSUE TITLE
Two values

### ISSUE THREAD

**Issue by cvelele** [Stryzhevskyi/rangeSlider#22]
Is it possible that slider have two values changing ?
One is under and changing while you slide, to have another one above and changing months (January, February ,,) or some other stuff ( days, years, kg ...) while you slide?

thx

**Comment by Stryzhevskyi** [comment]
From description it seems possible.
Take a look at [readme > Usage](https://github.com/Stryzhevskyi/rangeSlider#usage), `onSlide` parameter. You can place any code there and manipulate DOM in any way you want (change textContent, position, etc..).
