### ISSUE TITLE
Safari iOS bug

### ISSUE THREAD

**Issue by mariusnohr** [Stryzhevskyi/rangeSlider#26]
Hi, 

The slider isn't working on my version of Safari iOS (latest version). It stopped working after version 0.4.1. No errors, so I'm not really sure what's going on. Also tested the demo page (http://stryzhevskyi.github.io/rangeSlider/), but same result.

Just worth checking. 

Any ideas?

**Comment by Stryzhevskyi** [comment]
Hi,
Is it working with version 0.4.4 ? Bug was related to #24's fix

**Comment by mariusnohr** [comment]
0.4.4 works great. Thanks a lot for a quick fix on this!
