### ISSUE TITLE
Strange behaviour in display:none div

### ISSUE THREAD

**Issue by godsdog** [Stryzhevskyi/rangeSlider#30]
I use the plugin on 2 input (range) elements. One is visible when loading the page. 
The other one after the user clicks on a tab menu. 

The slider in the hidden div (with display: none;) has a strange behaviour.
Its impossible to slide and the round circle is too far on the left side.

When I resize the browser, the second slider is working correctly.
I tried to trigger with: $(window).trigger('resize');
Both in the console or with the onInit: function (){$(window).trigger('resize');}
Only the resizing by hand on the browser solves this issue?!

Any idea what could be the reason? I think it has something to do with the display: none parent div, when I show the div on pageload, the second slider is working propperly.

**Comment by Stryzhevskyi** [comment]
Hi
Can't reproduce described issue. Try to use `update()` method after remove `display: none` from parent.

**Comment by Stryzhevskyi** [comment]
No response, closing it.
