### ISSUE TITLE
live colours?

### ISSUE THREAD

**Issue by mooseh** [Stryzhevskyi/rangeSlider#34]
im trying to add live colours based on their value of 1-3
this changes the fillColour but it doesnt change the actual element?

here is my code:

```
            rangeSlider.create(document.querySelectorAll('input[type="range"]'),{
                rangeClass: 'rangeSlider',
                borderRadius: 10,
                onInit: function(){
                    if(this.value == 3){
                        this.update({fillClass: 'bg-red'});
                    }
                    if(this.value == 1){
                        this.fillClass = "bg-green";
                        console.log(this);
                    }

                },
            });
```

**Comment by Stryzhevskyi** [comment]
It won't work like this, especially on `onInit` handler 😄 Use `onSlide` and try this approach [this](https://codepen.io/Stryzhevskyi/pen/dKXGvG).
`update` method  [doesn't handle `fillClass` property](https://github.com/Stryzhevskyi/rangeSlider/blob/master/src/range-slider.js#L195) .
