### ISSUE TITLE
Lock slider when it hit's specific number?

### ISSUE THREAD

**Issue by Fenny** [Stryzhevskyi/rangeSlider#39]
Hi,

I have a min 0 and max 100 but the value is on 50 and it cannot go under 50, how can I achieve this?
`
if (val == 50) {
	 return false;
}
`
Doesn't seem to work

**Comment by Stryzhevskyi** [comment]
Hi
Check this [example](https://jsfiddle.net/Stryzhevskyi/rpsa16fn/)

**Comment by Fenny** [comment]
You sir are a hero!
