### ISSUE TITLE
Creating a rangeSlider should not trigger a native "change" event

### ISSUE THREAD

**Issue by kontur** [Stryzhevskyi/rangeSlider#43]
**Example**
[example](https://jsfiddle.net/f150La36/1/)

**Describe the bug**
Creating a rangeSlider triggers a "change" event on the input. Simply creating the UI should not trigger an event.

**To Reproduce**
1. Load the example. 

**Expected behavior**
The event listener triggers when I'd expect it to not trigger.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.3
 - Browser All major vendors
 - Version Current versions

**Smartphone (please complete the following information):**
- Not tested

**Comment by Stryzhevskyi** [comment]
Thank you for contribution!
I've published version 0.4.9 with your fix.

**Comment by jesseko** [comment]
should this issue be closed now?

**Comment by Stryzhevskyi** [comment]
@jesseko, it should, I guess.
