### ISSUE TITLE
Touch Screen on mobiles not working?

### ISSUE THREAD

**Issue by denzBrade** [Stryzhevskyi/rangeSlider#7]
Hi Sergei,

I noticed that on your demo page, the slider is unresponsive on mobile.
Even with the options set to:

`startEvent: ['mousedown', 'touchstart', 'pointerdown'],`

`moveEvent: ['mousemove', 'touchmove', 'pointermove'],`

`endEvent: ['mouseup', 'touchend', 'pointerup'],`

Any ideas to rectify this?

Thanks
Denzil

**Comment by Stryzhevskyi** [comment]
No ideas, everything works fine on Nexus 5 and Chrome (with touch device emulation). Could you tell which device and browser have such issue, please?

Thanks

**Comment by denzBrade** [comment]
Hi Sergei,

Thanks for the reply, it allowed me to investigated this issue further. 
It seems that libraries such as 'Swiftclick.js & FastClick.js' was conflicting with the touch enabled feature on mobile phones.
Once these were refactored or removed on the specific page the touch feature worked fine.

Thanks

**Comment by Stryzhevskyi** [comment]
Would you mind if I close this issue?
