### ISSUE TITLE
Tested in CommonJS/Browserify environment?

### ISSUE THREAD

**Issue by mrmartineau** [Stryzhevskyi/rangeSlider#8]
I have been struggling to get this plugin to actually work in a CommonJS environment, have you tested it there? What is the plugin `export`ing?

To mitigate the problem, I have had to create a local copy of it and use that. I can submit as a PR if you like...

**Comment by Stryzhevskyi** [comment]
Hi.
Do you mean that line 10 should look like so:
`module.exports = factory();`
or problem with non existent `document`?

Sure, you can submit your PR.

**Comment by mrmartineau** [comment]
Hi @Stryzhevskyi, if line 10 should look that, why doesn't it?

**Comment by mrmartineau** [comment]
Thank you for fixing this. My local version of the plugin changed much more than you did. :+1:

**Comment by Stryzhevskyi** [comment]
You are welcome
